export const APPWRITE_DB_ID = process.env.EXPO_PUBLIC_APPWRITE_DB_ID!;
export const USERS_COLLECTION_ID = process.env.EXPO_PUBLIC_USERS_COLLECTION_ID!;
export const CONTACTS_COLLECTION_ID = process.env.EXPO_PUBLIC_CONTACTS_COLLECTION_ID!;
export const MESSAGES_COLLECTION_ID = process.env.EXPO_PUBLIC_MESSAGES_COLLECTION_ID!;
